{% set version = "16.0.5" %}

package:
  name: mlir-python-bindings
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
    sha256: 37f540124b9cfd4680666e649f557077f9937c9178489cea285a672e714b2863
    patches:
      # https://reviews.llvm.org/D99470
      - 0001-Support-cross-compiling-standalone-MLIR.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - llvmdev {{ version }}  # [build_platform != target_platform]
    - python                 # [build_platform != target_platform]
    - numpy                  # [build_platform != target_platform]
    - pybind11 >=2.8.0       # [build_platform != target_platform]
  host:
    - llvmdev {{ version }}
    - llvm {{ version }}
    - mlir  {{ version }}
    - zlib
    - python
    - numpy
    - pybind11 >=2.8.0
  run:
    - python
    - pyyaml
    - {{ pin_compatible("numpy") }}
    - mlir {{ version }}

test:
  imports:
    - mlir
    - mlir.ir
  commands:
    - test -f "$SP_DIR/mlir/ir.py"                               # [unix]
    - test -f "$SP_DIR/mlir/execution_engine.py"                 # [unix]
    - if not exist "%SP_DIR%"\\mlir\\ir.py exit 1                # [win]
    - if not exist "%SP_DIR%"\\mlir\\execution_engine.py exit 1  # [win]

about:
  home: https://mlir.llvm.org/docs/Bindings/Python/
  license: Apache-2.0 WITH LLVM-exception
  license_file: mlir/LICENSE.TXT
  license_family: Apache
  summary: Python Bindings for MLIR

extra:
  recipe-maintainers:
    - jim22k
